### ISSUE TITLE
Purpose of this repository/chart

### ISSUE THREAD

**Issue by jan-di** [PaloAltoNetworks/twistlock-defender-helm#3]
Hi, 

we saw that this Repository was created and contains a Helm chart do deploy Prisma Cloud Defender.
So far used the functionality reachable in the our tenant of the Prisma Cloud App to download the Twistlock Defender Helm chart and deployed this. As we compared the charts, we noticed that they use the same versions but have different contents/templates shipped.

In an internal support ticket (Case# 03213290) it was confirmed that both Charts are separately from each other. As this repository already contains features, that would be interesting for us, I would like to ask a few questions:

- Will this chart stay compatible with the chart from Prisma Cloud? (Currently, values are derived from the upstream Chart)
- Is it planned that is maintained on the same level as the upstream chart? Regarding version updates and new features
- Are there cases where we don't should use this chart and use the upstream chart instead?

Answers to those questions would help us to understand the situation better, thank you.

PS: Feel free to move this issue to a discussion if it fits better :-)

**Comment by jfmontufar** [comment]
Hi @jan-di 

The difference on this Chart and the one downloaded on Prisma Cloud is that this one is community supported, meanwhile the downloaded one is the official chart. Just included such statement in the README file

**Comment by jfmontufar** [comment]
@jan-di to answer your questions:
1. It should be compatible with the latest version as long as the community still supports this chart. Regularly the official chart does not change from each release.
2.  Yes it is planned to be maintained.
3. This chart uses External Secrets operator to handle secrets. If you use your own secrets management tool and start from the upstream you can do it, therefore it wouldn't involve the parts that are related to External Secrets management.

Hope that this solves your questions.
